import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/app/components/(Header)/Header"
import Footer from "@/app/components/Footer"
import { Toaster } from "@/app/components/ui/sonner"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <Toaster richColors/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
